#!/usr/bin/env bash
# PostToolUse hook: when `gh pr create` succeeds in a Claude Code Bash call,
# spawn a fresh detached `claude -p` (Opus 4.7) to review the PR and post
# the review as a GitHub PR comment. Non-blocking; exits 0 immediately.
#
# Register it in a project's .claude/settings.json rather than the global one,
# so it fires only for repos you want reviewed on every PR.
# Kill switch: export SKIP_PR_REVIEW=1.

set -u

# --- Force subscription auth --------------------------------------------------
# Hooks run as subshells that inherit Claude Code's environment. If
# ANTHROPIC_API_KEY is exported (e.g. from ~/.zshrc) the headless `claude -p`
# below silently bills to the API account instead of the Max subscription.
# Unset it (and friends) so the CLI falls back to the OAuth login in ~/.claude/.
if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "WARN: ANTHROPIC_API_KEY was set; unsetting to force subscription auth" >&2
  unset ANTHROPIC_API_KEY
fi
unset ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL

# --- Manual kill switch -------------------------------------------------------
[[ -n "${SKIP_PR_REVIEW:-}" ]] && exit 0

MODEL="claude-opus-4-7"

INPUT=$(cat)

RESULT=$(INPUT="$INPUT" python3 - <<'PY'
import json, os, re, sys
d = json.loads(os.environ.get("INPUT") or "{}")
if d.get("tool_name") != "Bash":
    sys.exit(0)
cmd = (d.get("tool_input") or {}).get("command", "") or ""
if "gh pr create" not in cmd:
    sys.exit(0)
out = (d.get("tool_response") or {}).get("stdout", "") or ""
m = re.search(r'https://github\.com/[^\s]+/pull/\d+', out)
if not m:
    sys.exit(0)
print(m.group(0))
print(d.get("cwd") or "")
PY
)

[ -n "$RESULT" ] || exit 0

PR_URL=$(printf '%s\n' "$RESULT" | sed -n '1p')
CWD=$(printf '%s\n' "$RESULT" | sed -n '2p')
[ -n "$PR_URL" ] || exit 0
[ -n "$CWD" ] || CWD=$(pwd)

LOGDIR="$HOME/.claude/logs/pr-review"
mkdir -p "$LOGDIR"
TS=$(date +%Y%m%d-%H%M%S)
PR_NUM=$(printf '%s' "$PR_URL" | grep -Eo '[0-9]+$')
LOG="$LOGDIR/${TS}-pr${PR_NUM}.log"

CLAUDE_BIN=$(command -v claude || true)
[ -n "$CLAUDE_BIN" ] || CLAUDE_BIN="$HOME/.local/bin/claude"

# --- Provenance footer --------------------------------------------------------
# Computed here (bash knows the invocation context; the headless session does
# not) and appended verbatim to the review comment so every review self-reports
# which worktree fired it, on which host, with which model, and — critically —
# which billing rail it used.
HOOK_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(cd "$CWD" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null || printf '%s' "$CWD")"
BRANCH="$(cd "$CWD" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
AUTH="subscription"; [[ -n "${ANTHROPIC_API_KEY:-}" ]] && AUTH="API KEY (billing separately!)"

# Log the diff size so an unexpectedly expensive Opus run is visible after the
# fact. (Advisory only — no auto-downgrade.)
CHANGED="$(cd "$CWD" 2>/dev/null && git diff --shortstat "$(git merge-base HEAD main 2>/dev/null)" 2>/dev/null | tail -1)"

FOOTER="

---
<sub>Generated by the \`pr-review-on-create\` hook \`${HOOK_PATH}\` on host \`$(hostname -s)\` · worktree \`${REPO_ROOT}\` · branch \`${BRANCH}\` · model \`${MODEL}\` · auth **${AUTH}** · $(date -u +%FT%TZ)</sub>"

PROMPT="You are running headlessly to review pull request ${PR_URL}.

Steps:
1. Run \`gh pr view ${PR_URL}\` for title, body, and metadata.
2. Run \`gh pr diff ${PR_URL}\` for the full diff.
3. Conduct a focused review against the project's CLAUDE.md standards. Prioritize:
   - Bugs and logic errors
   - Security issues
   - Violations of documented project rules
   - Missing tests for new behavior
   - Unclear or risky code
   Skip style nits and minor preferences.
4. Post the review as a PR comment by piping the body into \`gh pr comment ${PR_URL} --body-file -\`. The body MUST begin with these two lines, exactly:

       <!-- claude-pr-review -->
       ## Automated review by Claude Opus 4.7

   The HTML comment is a stable marker the /review-copilot skill uses to find this review (the comment is posted under the human's gh user, not a bot login, so login filtering does not work). Do not omit or alter the marker line.

   For findings tied to a specific line, start the bullet with \`**\\\`<path>:<line>\\\`** — <finding>\` (e.g. \`**\\\`app/models/user.rb:42\\\`** — Possible nil deref...\`) so /review-copilot can dedup against Copilot's inline comments by (path, line). Group these under a \`### Inline findings\` heading; put broader observations under \`### General notes\`.

   The body MUST end with exactly the following footer, verbatim, as its final lines — do not alter, reflow, or omit it:
${FOOTER}
5. Do not modify any files in the working tree."

echo "$(date -u +%FT%TZ) pr=${PR_URL} cwd=${CWD} model=${MODEL} auth=${AUTH} changed=[${CHANGED}]" >>"$LOG"

(
  cd "$CWD" 2>/dev/null || true
  nohup "$CLAUDE_BIN" -p --model "$MODEL" --max-turns 15 --dangerously-skip-permissions "$PROMPT" \
    >>"$LOG" 2>&1 </dev/null &
  disown
) &

exit 0
